#!/bin/sh
MIRROR=${MIRROR:-/mirror}
ALLOW=${ALLOW:-192.168.0.0/16 172.16.0.0/12}
OWNER=${OWNER:-nobody}
GROUP=${GROUP:-nogroup}

chown "${OWNER}:${GROUP}" "${MIRROR}"

[ -f /etc/nginx/conf.d/default.conf ] || cat <<EOF > /etc/nginx/conf.d/default.conf
server {
  listen 80 default_server;
  listen [::]:80 default_server;
  
  # Everything is a 404
  root ${MIRROR};
  
  $(for a in ${ALLOW}; do echo "allow ${a};"; done)
  deny all;
  
  autoindex on;
  access_log /dev/stderr;
  error_log /dev/stdout;
}
EOF

#change directories for the mirror
cd ${MIRROR}

# do the mirror in the background
wget -o wget-log -mkEpnp -nH "http://packages.instantos.io/" &

# setup crontab for every 15th minute
echo "*/15 * * * * wget -o wget-log -mkEpnp -nH "http://packages.instantos.io/" &" | crontab -

# start nginx
nginx -g 'daemon off; pid /run/nginx.pid;' &

CMD ["cron", "-f"]
